### ISSUE TITLE
1.8.1拖拽文件至 UACWhitelistTool 窗口无效

### ISSUE THREAD

**Issue by theluanr** [XIU2/UACWhitelistTool#10]
RT

PS:拖动文件操作如果在“浏览”按钮上松开，会触发“浏览”按钮的 click 事件

**Comment by XIU2** [comment]
奇怪，我只是把检查更新代码注释掉了，怎么会导致拖放文件功能失效咧。。。我研究下

****

> PS:拖动文件操作如果在“浏览”按钮上松开，会触发“浏览”按钮的 click 事件

这个问题我无法复现。

**Comment by XIU2** [comment]
排查后发现，是在 2020 年 10 月，我更新过一次代码（但并没有更新软件版本），其中的一个小改动导致了该问题，但我已经记不清当初为什么要改了。。。

不过总归问题是解决了，已更新版本：
https://github.com/XIU2/UACWhitelistTool/releases/tag/v1.8.2

**Comment by theluanr** [comment]
dalao nb！
