### ISSUE TITLE
计划任务动态传参能否实现

### ISSUE THREAD

**Issue by ZetaSp** [XIU2/UACWhitelistTool#2]
计划任务好像支持传入参数。
在我的电脑上看到有个计划这么写的参数：$(Arg0) /tasksch
![image](https://user-images.githubusercontent.com/36418285/107881755-a56db880-6f20-11eb-8086-cff40fca64c9.png)
（是 Uninstall Tool 软件的自动跳 UAC，也支持右键菜单）
看起来是动态传入的。
不过 schtasks 并没有传入这样参数的选项，据[微软文档](https://docs.microsoft.com/zh-cn/windows/win32/taskschd/task-actions#using-variables-in-action-properties)说的，调用 C++ API 可以传参，也许可以把快捷方式指向一个专门传参数的 C++ 程序来动态传参启动。

**Comment by ZetaSp** [comment]
除此之外，我还找出个动态传参的旁门左道😀。在计划任务里启动一个单行的批处理，读取一个临时文件并执行里面写的程序带参数。不过很不安全，随便哪个程序都可以跳 UAC 了。

**Comment by XIU2** [comment]
微软 API 那个没有示例我这半吊子技术也看不太懂。

****

不过你这个旁门左道，就是麻烦一些，先通过快捷方式免 UAC 启动脚本（批处理）后，然后再去指定要启动的程序。

理想状态是让这个脚本或者程序变成一个**免 UAC 启动器**，只需要添加这个启动器到计划任务中，然后动态传参方式启动这个启动器，启动器再根据参数去启动相应的程序，参数可以直接是路径，也可以是本地搞个配置文件记录各程序路径。

因为动态传参没搞明白，所以就没办法。。。

****

至于安全性，则不需要考虑那么多，因为 [UAC 漏洞](https://github.com/hfiref0x/UACME)目前已知的就有几十个还没修复，病毒之类的程序有的是办法跳过 UAC，而对于普通的程序，有些不给 UAC 就直接不给你用，所以我这个软件的开发目的就是为了解决 UAC 和方便不可兼得的问题。

**Comment by ZetaSp** [comment]
我做了个能传参的。[sUdoAC](https://github.com/ZetaSp/sUdoAC)
目前好像创建快捷方式有点 bug，但是可以用附赠的 sudo 命令运行。
