### ISSUE TITLE
打开快捷方式后软件没有运行

### ISSUE THREAD

**Issue by KiDrain61** [XIU2/UACWhitelistTool#6]
只在任务栏闪现了一个格子并迅速消失，此外没有其他反应，请问可能是什么问题导致的呢？

**Comment by XIU2** [comment]
我没遇到过，所以也并不清楚。

你尝试在计划任务里手动右键运行试试。

**Comment by KiDrain61** [comment]
手动创建了一个任务计划，发现可以使用。结果试了试原来生成的快捷方式，也可以使用了...感觉很奇怪。总之问题暂时解决啦，感谢提示！
