### ISSUE TITLE
检查更新异常

### ISSUE THREAD

**Issue by yfdyh000** [XIU2/UACWhitelistTool#7]
打开后始终
```
---------------------------
发现新版本！
---------------------------
发现新版本 [v        rel="icon"]！是否前往更新？
---------------------------
是(Y)   否(N)   
---------------------------

```
https://github.com/XIU2/UACWhitelistTool/blob/f77f0fc950496b98637582ffaebb9624d0430c17/Form.cs#L283

https://api.xiuer.pw 已失效。

**Comment by XIU2** [comment]
这个域名已经放弃 1 年了好像，集中到另一个域名了。

而且该软件也基本不会再更新了，你在 hosts 中加入以下内容来屏蔽检查更新吧：
```
0.0.0.0 api.xiuer.pw
```

**Comment by XIU2** [comment]
算了，我直接发布了个 v1.8.1 版本，移除了检查更新功能。
